name: learn-github-actions

run-name: ${{ github.actor }} is testing github actions.

on:
  schedule:
    - cron: "18 * * * *"
    - cron: "20 * * * *"

jobs:
  see-github-object-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
      - run: echo $min
      - run: $min++
      - run: echo $min
      - run: echo ${{github}}
